#!/bin/bash

echo "🚂 RAILWAY DEPLOYMENT GUIDE"
echo "==========================="
echo ""

echo "💰 Why Railway?"
echo "• $5/month for 8GB RAM + 8 vCPU"
echo "• Free $5 credit monthly"
echo "• Simple Git-based deployment"
echo "• Automatic HTTPS & custom domains"
echo "• Built-in environment variables"
echo "• Zero-config deployments"
echo ""

echo "🚀 Quick Railway Setup:"
echo ""

echo "1️⃣ CREATE RAILWAY ACCOUNT"
echo "   Go to: https://railway.app"
echo "   Sign up with GitHub (recommended)"
echo ""

echo "2️⃣ INSTALL RAILWAY CLI (Optional)"
echo "   npm install -g @railway/cli"
echo "   railway login"
echo ""

echo "3️⃣ DEPLOY FROM GITHUB"
echo "   • Go to railway.app dashboard"
echo "   • Click 'New Project'"
echo "   • Select 'Deploy from GitHub repo'"
echo "   • Choose your repository"
echo "   • Railway auto-detects Node.js!"
echo ""

echo "4️⃣ SET ENVIRONMENT VARIABLES"
echo "   In Railway dashboard → Variables tab:"
echo ""
echo "   BOT_TOKEN=your_telegram_bot_token"
echo "   ZOOM_CLIENT_ID=your_zoom_client_id"
echo "   ZOOM_CLIENT_SECRET=your_zoom_client_secret"
echo "   ZOOM_SECRET_TOKEN=your_zoom_secret_token"
echo "   ZOOM_REDIRECT_URI=https://your-app.railway.app/auth/zoom/callback"
echo "   PORT=3000"
echo ""

echo "5️⃣ AUTOMATIC DEPLOYMENT"
echo "   • Railway automatically deploys on Git push"
echo "   • Build logs available in dashboard"
echo "   • Custom domain available"
echo ""

echo "💡 COST BREAKDOWN:"
echo "   • Free tier: $5 credit/month"
echo "   • Hobby plan: $5/month"
echo "   • Usage-based billing"
echo "   • Sleep mode saves costs"
echo ""

echo "🔧 RAILWAY ADVANTAGES:"
echo "   ✅ Cheaper than Heroku"
echo "   ✅ Better than free tiers"
echo "   ✅ Auto-scaling"
echo "   ✅ Built-in monitoring"
echo "   ✅ Easy Git integration"
echo "   ✅ Custom domains included"
echo ""

echo "🚂 READY TO DEPLOY?"
echo "1. Push code to GitHub"
echo "2. Connect Railway to repo"
echo "3. Set environment variables"
echo "4. Deploy automatically!"
echo ""

echo "📱 Your bot will be live at:"
echo "https://your-app-name.railway.app"
echo ""

echo "🎉 Railway deployment ready!"
