# 🎨 Render Configuration
# Static site build for docs and admin panel

services:
  - type: web
    name: nebulosa-docs
    env: static
    buildCommand: npm run build:docs
    staticPublishPath: ./docs-build
    routes:
      - type: rewrite
        source: /docs/*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: DOCS_MODE
        value: static

  - type: web  
    name: nebulosa-admin
    env: node
    buildCommand: npm install
    startCommand: node admin-panel.js
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: nebulosa-db
          property: connectionString

  - type: web
    name: nebulosa-backup-bot
    env: node  
    buildCommand: npm install
    startCommand: node backup-bot.js
    plan: free
    region: oregon
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: backup
      - key: BOT_TOKEN
        fromGroup: bot-secrets
      - key: BACKUP_MODE
        value: true

databases:
  - name: nebulosa-db
    databaseName: nebulosa
    user: nebulosa_user
    plan: free
    region: oregon

# Build settings for docs
build:
  - name: docs
    buildCommand: |
      npm install
      npm run generate:docs
      npm run build:static
    publishDir: docs-build
    
# Environment groups
envVarGroups:
  - name: bot-secrets
    envVars:
      - key: BOT_TOKEN_BACKUP
        value: # Set in Render dashboard
      - key: ZOOM_CLIENT_ID  
        value: vGVyI0IRv6si45iKO_qIw
      - key: RENDER_WEBHOOK_SECRET
        generateValue: true
